version: '3.4'

services:
  ehotelsappbackend:
    image: ehotelsappbackend
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
